baseurl = "https://fengmao.netlify.app"
title = "不正经拳论"
author = ""
canonifyurls = true
locale = "cn"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "不正经拳论"
  disableWebFonts = false

[[menu.main]]
    name = ""
    url  = ""

