#+title: 孙门内劲练法
#+TAGS[]: 内劲今解
#+date: <2026-09-14 一>

我前面用了很多文字讲一气，讲金丹，讲内劲。

当年的孙禄堂先生也一样，用了很多篇幅从不同的角度试图讲明白什么是拳中内劲。

孙先生在《拳意述真》中写道：
#+begin_quote
“拳中之内劲是将人之散乱于外之神气，用拳中之规矩，手足身体动作，顺中用逆缩回于丹田之内，与丹田之元气相交，自无而有，自微而著，自虚而实，皆是渐渐积蓄而成，此谓拳之内劲也。”
#+end_quote
** 散乱的神气
 内劲来自于我们人人本自俱足的神气，只不过没有练过的人，这些神气是散乱在外的。
“散乱于外的神气"中的“神”我在[[id:lianjing][《炼精化气炼气化神》]]中已经做了简单的解释。拳术中的神就是我们一切感知的综合。

而散乱于外的神，是指我们初学拳的人心神是不定的，感知是到处乱跳的。一会感觉这里酸，一会觉得那里痛，一会好像前面那人在看你，一会又觉得身后有个小动物经过等等。而把这个散乱的神收起来，其实就是放弃主动感知，切换成被动感知模式。

其情形有点像是手术台上被全身麻醉，但却头脑清醒的的病人，反正一动也不能动，啥 也干不了，干脆彻底摆烂，就静静地在那听着，看着，感受着身体内外发生的一切。

一旦进入这个状态，你的神就收回来了。当你的神收回来，不再在身内外各种事物上乱跳的时候，你就会发现你的感知范围其实是以你为中心的圆球，所以孙门心法叫“神圆”。

而只是被动充分感受，不加任何干涉，恰如天上挂了一面大镜子，把你身体内外的东西，事无巨细，全给照进去了。这就是“神如昊镜”。也叫“用心若镜”，这里的心就是神，心藏神明。

“散乱于外的神气”中的“气”是先天真一之气的雏形，也是不知不觉间自动平衡的能力，但这是局部的，不是整体的 。由于我们后天的不良习性，导致它们分散在身体各处，各自为政，彼此之间不能相互联络照应。也有人称之为后天气。

缩回丹田就是打通它们和丹田之间的通道，再交给丹田的元气托管。就是先天真一之气了，也就是拳中内劲了。
** 顺中用逆
练习方法是：“用拳中规矩，手足身体动作，顺中用逆缩回于丹田”。

拳中规矩就是孙氏拳的九要，手足身体动作就是孙氏拳架，顺中用逆是我们讲过多次的“手足顺其自然往前伸，气力往回缩”。

手足顺其自然往前伸，气力它会同时自动往回逆缩。这个顺伸和逆缩它们是同时进行的，它们是一个东西，不是两个东西。

不过顺中用逆的确比较难理解，因为它是个通理。就是文字浅显，但内涵极深。

从最浅显的角度讲，就是你放松，顺其自然不用力把手往前伸，伸到极限，是不是有东西拉住，往回缩？那个往回缩的东西就是“气力”。这是每一个人无论练不练拳静下心来都能体会到的。

你用筷子去夹豆花吃，就是顺伸逆缩。你不往前伸，够不着豆花；你不把劲收回来，豆花又让给你夹断了。

文字已经写得再直白不过了，但很多人就是不相信这么简单能练出内劲来。

有人解释成“用意缩回于丹田之内”，也不能说他错，但要明白这里的意不是后天意念，而是先天真意,，我在[[id:wuyi][《无意之中是真意》]]中有过阐述。如果不明白这一点，就直接无视这个“意”就好了。

气力会缩到哪里？缩到你手足能通到的地方，我们手足能通到的终点就是小腹，也即丹田。

一般人一开始手通不到丹田，也许只能收到肘，到肩。通过无极式，慢慢练习，才能收到丹田。

那怎么知道收进去了，收到哪儿了呢？其实练的人自己知道。仔细体会下，夹豆花是在用手夹，还是用肩夹，还是用丹田夹？每个人身体的通透程度不一样，他们的感受也不一样。

丹田是人体处于静止状态下，唯一还能自动运作的部位，这是从娘胎里带来的功能，古人称之为元气。与丹田元气相交，就是交给丹田托管。

丹田俗称气海，也就是多少气收进去都如泥牛入海，不会出现小腹胀满的情况，宋世荣先生称之为“有若无，实若虚”。

内劲有腹内压，核心肌群的参与，但它不是腹内压或核心力量。那些人为鼓动丹田发力，抗击打的都不是孙氏拳的内劲。

顺中用逆即是祛病强身之道。可以解决一切练拳或其它功法碰到的问题，切勿等闲视之。

** 星星之火
“自无而有，自微而著，自虚而实，皆是渐渐积蓄而成”，也就是说这个内劲它是一点点慢慢培养起来的，一开始就像个小火星，慢慢地培养成小火苗，最后成了熊熊大火才能拿去烧东西。

因此初学内家拳，不要去和不懂的人推手交流。你刚能把你的气力收回来一点点，还是个小火星，结果人家蛮力直接压过来，把你小火星给熄了。你想羸人家，也得把自己的小火星掐了和人家拼蛮力才行，就和内家拳南辕北辙了。

懂的老师这时候会慢慢培养你的小火苗，等到它足够壮大再让你去和人交流。
** 玄关一窍
关于孙先生的这段话，太极芸庄老师其实解释得很不错的，但她只讲到了缩，没讲到里面的中。

没有中的话怎么缩也只是在缩后天气，而得不到先天一气（内劲）。也只是停留在修心养性层面，还谈不上功夫。

气力往回缩，往里缩，往身体最深处缩，往丹田缩。但最终必须把那个“中”给缩出来，否则就像过河迷上了划船，而不肯登岸一样。

孙氏拳讲究：不丢轴，不离缩。也就是必须得有中，其缩才有依据。

这个中就是先天一气在拳中的体现，也即玄关一窍，即玄牝。

结合前面讲到的“用心若镜”，就是孙门的口诀：“在身为轴，用心若镜”。

懒腰我们都伸过，它就是不丢轴，不离缩，手足自然伸出，气力自动缩回。这就是身体自发的内功。

无极式往那一站，重心坐满在脚后跟，将倒不倒。就是顺中用逆，始终处于伸懒腰的状态。就是得内劲的不二法门。

得内劲的人往往有两个很有意思的特征：

一是常常会自发伸懒腰，尤其是早上睡醒后。

二是随随便便一伸手，普通人挡不住。
