#+title: 练拳大忌之烧干锅
#+TAGS[]: 杂谈
#+date: <2026-09-14 一>

我们把不得一气而强练称为“烧干锅”。

而烧干锅又分两种情况，一种是功夫不到还强行模仿高手猛打拳猛发力，另一种则是强行用意念乱走气。

这二者都有一个共同特点就是，练的时候感觉非常好，热血澎湃，气感强烈。但练完后体虚畏寒，收摄不住。

练拳的人，防风如防箭，防寒如防枪。练完后不碰凉水，不吹空调风扇本是很正常的现象。但烧干锅的人会夸张到不肯和身体虚寒的人接触，甚至和他们站在一块都会有被他们吸走能量的感觉。这就是收摄不住。

经常会看到一些老拳师和人说拳的时候，对方都不戴手套，他却戴个手套。这种也是收摄不住，所以戴个手套保护一下。但未必是烧干锅，也有可能是练功练过了，或者受了其它内伤。

烧干锅还会伴随其他症状，比如容易虚热，爱出虚汗，某些地方特别怕冷，有隐痛，体虚却难以节制欲望等等。有的人练到后面都不敢练了，所谓练拳招邪就是这么来的。这还都是轻的。

不得气猛打拳，还可能造成永久性损伤。有些伤一旦造成，就再也修复不了的。比如膝盖骨上韧带的撕裂，它是再也长不回去的，只能避免使用它而防止造成进一步损伤。有些老前辈功夫很大，也修复不了旧伤，只能带伤共存，绕开伤用他的功夫。功到病成讲的就是这个。

意念乱走气则可能导致疝气，癫痫，甚至莫名奇妙的内脏受伤。还有人拿气乱冲脊柱乃至脑部的会导致各种神经相关的问题，甚至癫狂。古人讲的走火入魔就是这个。

烧干锅的本质就是以违背人体生理规律的方式强行折腾身体导致身体受了内伤。

这里所说的内伤，不是指那种被重击导致里面受伤那种伤，那种还是外伤，因为是外力强行击打所致。

这里的内伤是长期错误锻炼一点一点积累起来的，体内深层小肌肉，小筋膜持续受伤。


怎么避免烧干锅呢？练的时候要如孙禄堂先生所说：“纯任自然，不加一丝血气”。而练出东西来了要如宋世荣先生所说：“有若无，实若虚”。就是练出来什么就要丢掉什么，狗熊掰棒子，掰一个丢一个。舍不得丢掉就要受伤。

我们练拳一定会出体感，但不要拘泥于那个体感，过一会它自己就没了，又会有新的体感出现。其实是在不断激活新的小筋膜。如果你一直追求某种确定的体感，那就会因反复折腾某些小筋膜而致伤。自我拳感很好，但却越练越虚。

如果已经受伤，怎么解决呢？

如果形成了病灶，就去看西医；如果还没有形成病灶，西医是看不了的。一般的中医也治不了，因为这不是普通人会受的伤。

练拳导致的伤还只能通过拳来治。应当立即停止练习当前在练的拳，找真懂拳的老师，让老师帮忙诊断问题，调整练法，或者改练更合理的功法。

如果附近没有明白的老师怎么办？清空一切以前所学，从头开始站孙氏无极式。孙氏无极式逆返天，其顺中用逆，无知无觉间自动平衡的能力，可以平衡身体内的这种不平衡。
