#+title: 大道至简之无极式
#+TAGS[]: 形意拳
#+date: <2026-09-08 二>

如果说三体式是形意拳的总机关，无极式就是孙氏三拳入道的总机关。
* 拳术道学化之弊
一直有很多人诟病孙禄堂先生将拳术道学化。拳术作为一门实用技艺，非要和无极，太极，阴阳，五行，八卦这些玄之又玄的概念扯在一块。


这里考虑到古人的局限，他们不像我们现在有很多科学的概念，要讲清楚一个东西，只能借用太极阴阳那套古人常用的话语体系。以今天的眼光去评判古人，未免也太苛责古人了。


而搞懂前人的东西，并将其用科学的语言讲清楚，不正是我们现代人的责任？


孙禄堂先生在他的几部拳剑著作里，开篇即是无极学，无一例外，其重要性可见一斑。

* 太极阴阳今解
极，就是极点。


无极，就是开天辟地之前，天地混沌一片，连那个极都不存在。


太极，就是非常极，极已经存在了并接近临界点，过了这个临界就要分裂成阴阳了。


两仪，就是阴阳，有了阴阳就有了万物，万物都是由阴阳组成的。


对万物的属性进一步细分就衍生出了四象，八卦。八卦还可以进一步演化到六十四卦以至于无穷多。

另外一个描述方法就是道生一，一生二，二生三，三生万物。这里道即无极，一即太极，二即阴阳，三遍指所有的阴阳组合，因此三生万物。


而根据万物不同的特征，古人又归纳出金木水火土五种相生相克的属性，以这五个概念来描述它们之间相互转化的关系。

还有先天，后天之说。

先天，就是有天以前，无极就是先天。

后天，就是有天之后，太极、两仪等后面形态都属于后天。

* 太极阴阳和拳
这套理论应用在拳术里：
+ 无极就是拳术尚不存在，我们人体处于混沌一片的状态
+ 太极就是极点已经出现，拳术将要产生
+ 阴阳就是拳中的种种形式和变化


太极拳分到这它就不往下分了，它就拿住这个阴阳玩。


形意拳则认为有一种阴阳的组合最能代表拳，它就是三体式，而后所有的拳式和变化都由它而来。


八卦掌则进一步细分为四象八卦以更细致地描述拳中动作。

* 无极学简述
而我们这里要讲的无极，是人练拳之前所处的混沌状态。而正是这个状态被孙禄堂先生描述为“逆运先天真一之气”， 而这个先天真一之气是人的“性命之根，造化之源， 生死之本，形意拳之基础也”。


所谓先天真一之气，就是太极，是人体所能达到的最舒适也最健康的状态。拳术动作都是在这个状态下衍生出来的。这个状态怎么达到呢？站孙氏无极式。


孙氏无极式形式极为简洁，总结一下也就两点：
+ 形：两脚后跟并拢，两脚成九十度自然站立。
+ 意：空空静静，身体不受力就是空，大脑不对身体加以控制，只客观感知身体的变化，就是静。

进一步了解“空”，可参见[[id:songchen][《松沉空无》]]。

童旭东先生讲：无极式是锻炼人无之无觉间自动平衡的能力。无极式本身是静，而产生的这种自动平衡的能力就是静中动。


先平衡自身，即顺中用逆，是练体。也就是祛病强身，站无极能让身体自动修复，很多人处于亚健康，身上有隐疾，都能得到解决。它甚至有助于一些重大疾病的康复。这和中医的医理是相通的，中医就是用针药调节人体的平衡。


再平衡他人，即逆中行顺，是练用。孙家拳打人就是这个，也就是对方不是被我主动打出去的，而是因为试图攻击我，被我无知无觉间自动平衡的能力自动反击的。也叫“神行机圆人莫能胜”。孙家拳没有发力，因为它从不主动打人。


平衡自身最初的作用就正身，站出身上那根中轴来(参见[[id:zhong][《内家拳的中》]])。中轴的体感参见[[id:zhonghe][《孙氏拳之中和》]]。

中轴一出来基本上就算摸到内家拳的大门了。

* 无极学和道家思想
无极式的体用，完全符合无为无不为，不用之用是为大用的道家思想。


张至顺道长曾讲：要得先天真无极，脑袋放到肚子里。这里有两层意思：
+ 中轴出来以后，由于人是自然随重力下沉的，上虚下实，有种脑袋和肚子一体的体感。这是空的作用
+ 练拳时头脑放弃控制，一切全凭丹田作主。为什么是丹田，因为丹田是人在静止状态下唯一还在动的部位。 这是静的作用。


无极内涵极深，这里只涉及其九牛一毛，如需了解更多请进一步参考童旭东，孙剑云等先生的著作。
